#!/bin/bash -e

source $REPO/setenv

pkgname=opencascade
pkgver=dev

tmpdir=$REPO/tmp/$pkgname
srcdir=$tmpdir/oce
reldir=opt/$pkgname-$pkgver
destdir=$REPO/$reldir

prepare()
{
  mkdir -pv $tmpdir && pushd $tmpdir
  git clone https://github.com/tpaviot/oce.git
  popd
}

configure()
{
  [[ -d $srcdir/build ]] && rm -rf $srcdir/build
  mkdir -pv $srcdir/build && pushd $srcdir/build

  cmake \
    -D OCE_INSTALL_PREFIX:PATH=$destdir \
    -D OCE_DRAW:BOOL=ON \
    -D OCE_MULTITHREAD_LIBRARY:STRING="TBB" \
    ../
 
  popd
}

build()
{
  pushd $srcdir/build
  make -j8
  popd
}

package()
{
  # remove old installation
  [ -d $destdir ] && rm -rfv $destdir
  # install new one
  pushd $srcdir/build
  _pythonver=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
  mkdir -pv $destdir/lib/python$_pythonver/site-packages
  export PYTHONPATH=$destdir/lib/python$_pythonver/site-packages:$PYTHONPATH
  make install
  popd
  pushd $destdir
  cat << EOF > setenv
export OCE_DIR=\$REPO/$reldir
export CASROOT=\$OCE_DIR
PATH=\$OCE_DIR/bin:\$PATH
DYLD_LIBRARY_PATH=\$OCE_DIR/lib:\$DYLD_LIBRARY_PATH
EOF
  popd
}

clean()
{
  rm -rfv $tmpdir
}

