#!/bin/bash

export REPO=$HOME/fenics/pkgs

setpkg()
{
  echo "Setting $1-$2 ..."
  pkgdir=$REPO/opt/$1-$2
  if [ ! -d "$pkgdir" ]; then
    echo "!!! Package not found"
    return
  fi
  source $pkgdir/setenv
}

setpkg metis 5.1.0
setpkg parmetis 4.0.3
setpkg suitesparse 4.2.1
setpkg superlu 4.3
setpkg superlu_dist 3.3
setpkg scalapack 2.0.2
setpkg scotch 6.0.0
setpkg mumps 4.10.0
setpkg hypre 2.9.1a
setpkg trilinos 11.4.1

export PATH=${PATH%:}
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH%:}
export DYLD_FRAMEWORK_PATH=${DYLD_FRAMEWORK_PATH%:}
export INFOPATH=${INFOPATH%:}
export MANPATH=${MANPATH%:}
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH%:}
export PYTHONPATH=${PYTHONPATH%:}

