#!/bin/bash

export REPO=$HOME/fenics/pkgs

setpkg()
{
  #echo "Setting $1-$2 ..."
  pkgdir=$REPO/opt/$1-$2
  if [ ! -d "$pkgdir" ]; then
    echo "!!! Package not found"
    return
  fi
  source $pkgdir/setenv
}

# CUDA
export PATH=$PATH:/usr/local/cuda/bin
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/cuda/lib

# export everything
export PATH=${PATH%:}
export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH%:}
export DYLD_FRAMEWORK_PATH=${DYLD_FRAMEWORK_PATH%:}
export INFOPATH=${INFOPATH%:}
export MANPATH=${MANPATH%:}
export PKG_CONFIG_PATH=${PKG_CONFIG_PATH%:}
export PYTHONPATH=${PYTHONPATH%:}

