#!/bin/bash -e

pkgname=arpack
pkgver=dev

tmpdir=$REPO/tmp/$pkgname
srcdir=$tmpdir/$pkgname-ng
reldir=opt/$pkgname-$pkgver
destdir=$REPO/$reldir

prepare()
{
  mkdir -pv $tmpdir && pushd $tmpdir
  if [ -d "arpack-ng" ]; then
    pushd $srcdir
    git pull
    popd
  else
    git clone git://git.forge.scilab.org/arpack-ng.git
  fi
  popd
}

configure()
{
  pushd $srcdir

  ./configure \
    F77="mpif77" \
    --prefix=$destdir \
    --enable-mpi
  popd
}

build()
{
  pushd $srcdir
  make \
    F77="mpif77" \
    FFLAGS+=" -m64" \
    CFLAGS+=" `pkg-config --cflags ompi` " \
    LIBS+=" `pkg-config --libs ompi` "
   popd
}

package()
{
  # remove old installation
  [ -d $destdir ] && rm -rfv $destdir
  # install new one
  pushd $srcdir
  make install
  popd
  pushd $destdir
  cat << EOF > setenv
export ARPACK_DIR=\$REPO/$reldir
PATH=\$ARPACK_DIR/bin:\$PATH
DYLD_LIBRARY_PATH=\$ARPACK_DIR/lib:\$DYLD_LIBRARY_PATH
PKG_CONFIG_PATH=\$ARPACK_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH
MANPATH=\$ARPACK_DIR/share/man:\$MANPATH
EOF
  popd
}

clean()
{
  rm -rfv $tmpdir
}

prepare
configure
build
package
#clean
