#!/bin/bash -e

source $REPO/setenv

pkgname=gmsh
pkgver=dev

tmpdir=$REPO/tmp/$pkgname
srcdir=$tmpdir/gmsh
reldir=opt/$pkgname-$pkgver
destdir=$REPO/$reldir

prepare()
{
  mkdir -pv $tmpdir && pushd $tmpdir
  svn co https://geuz.org/svn/gmsh/trunk gmsh
  popd
}

configure()
{
  [[ -d $srcdir/build ]] && rm -rf $srcdir/build
  mkdir -pv $srcdir/build && pushd $srcdir/build

  export CASROOT=$OCE_DIR

  cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=$destdir \
    -D ENABLE_MPI:BOOL=ON \
    -D CMAKE_BUILD_TYPE:STRING="Release" \
    -D ENABLE_OS_SPECIFIC_INSTALL:BOOL=OFF \
    ../
 
  popd
}

build()
{
  pushd $srcdir/build
  make -j5
  popd
}

package()
{
  # remove old installation
  [ -d $destdir ] && rm -rfv $destdir
  # install new one
  pushd $srcdir/build
  _pythonver=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
  mkdir -pv $destdir/lib/python$_pythonver/site-packages
  export PYTHONPATH=$destdir/lib/python$_pythonver/site-packages:$PYTHONPATH
  make install
  popd
  pushd $destdir
  cat << EOF > setenv
export GMSH_DIR=\$REPO/$reldir
PATH=\$GMSH_DIR/bin:\$PATH
PYTHONPATH=\$GMSH_DIR/lib/python$_pythonver/site-packages:\$PYTHONPATH
PKG_CONFIG_PATH=\$GMSH_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH
DYLD_LIBRARY_PATH=\$GMSH_DIR/lib:\$DYLD_LIBRARY_PATH
EOF
  popd
}

clean()
{
  rm -rfv $tmpdir
}

