#!/bin/bash -e

pkgname=python-ufc
pkgver=dev

tmpdir=$REPO/tmp/$pkgname
srcdir=$tmpdir/ufc
reldir=opt/$pkgname-$pkgver
destdir=$REPO/$reldir

prepare()
{
  mkdir -pv $tmpdir && pushd $tmpdir
  if [ -d $srcdir ]; then
    pushd $srcdir
    git pull
    popd
  else
    git clone git@bitbucket.org:fenics-project/ufc.git
  fi
  popd
}

configure()
{
  [[ -d $srcdir/build ]] && rm -rf $srcdir/build
  mkdir -pv $srcdir/build && pushd $srcdir/build

  export BOOST_ROOT=$BOOST_DIR
  cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=$destdir \
     ../
  
  popd
}

build()
{
  pushd $srcdir/build
  make
  popd
}

package()
{
  # remove old installation
  [ -d $destdir ] && rm -rfv $destdir
  # install new one
  pushd $srcdir/build
  _pythonver=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
  mkdir -pv $destdir/lib/python$_pythonver/site-packages
  export PYTHONPATH=$destdir/lib/python$_pythonver/site-packages:$PYTHONPATH
  make install
  popd
  pushd $destdir
  cat << EOF > setenv
export UFC_DIR=\$REPO/$reldir
PATH=\$UFC_DIR/bin:\$PATH
PYTHONPATH=\$UFC_DIR/lib/python$_pythonver/site-packages:\$PYTHONPATH
PKG_CONFIG_PATH=\$UFC_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH
EOF
  popd
}

clean()
{
  rm -rfv $tmpdir
}

prepare
configure
build
package
#clean
