#!/bin/bash -e

pkgname=dolfin
pkgver=dev

tmpdir=$REPO/tmp/$pkgname
srcdir=$tmpdir/dolfin
reldir=opt/$pkgname-$pkgver
destdir=$REPO/$reldir

prepare()
{
  mkdir -pv $tmpdir && pushd $tmpdir
  if [ -d $srcdir ]; then
    pushd $srcdir
    git pull
    popd
  else
    git clone git@bitbucket.org:fenics-project/dolfin.git
  fi
  popd
}

configure()
{
  [[ -d $srcdir/build ]] && rm -rf $srcdir/build
  mkdir -pv $srcdir/build && pushd $srcdir/build

  cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=$destdir \
    -D CMAKE_SHARED_LINKER_FLAGS:STRING="-L$MUMPS_DIR/lib -ldmumps" \
    -D SCOTCH_DIR:PATH=$SCOTCH_DIR \
    -D PETSC_DIR:PATH=$PETSC_DIR \
    -D TAO_DIR:PATH=$TAO_DIR \
    -D SLEPC_DIR:PATH=$SLEPC_DIR \
    -D AMD_DIR:PATH=$SUITESPARSE_DIR \
    -D UMFPACK_DIR:PATH=$SUITESPARSE_DIR \
    -D CHOLMOD_DIR:PATH=$SUITESPARSE_DIR \
    -D TRILINOS_DIR:PATH=$TRILINOS_DIR \
    -D PARMETIS_DIR:PATH=$PARMETIS_DIR \
    -D PASTIX_DIR:PATH=$PASTIX_DIR \
    -D DOLFIN_ENABLE_OPENMP:BOOL=OFF \
    ../
  
  popd
}

build()
{
  pushd $srcdir/build
  make -j5
  popd
}

package()
{
  # remove old installation
  [ -d $destdir ] && rm -rfv $destdir
  # install new one
  pushd $srcdir/build
  _pythonver=`python -c 'import sys; print("%d.%d" % sys.version_info[:2])'`
  mkdir -pv $destdir/lib/python$_pythonver/site-packages
  export PYTHONPATH=$destdir/lib/python$_pythonver/site-packages:$PYTHONPATH
  make install
  popd
  pushd $destdir
  cat << EOF > setenv
export DOLFIN_DIR=\$REPO/$reldir
PATH=\$DOLFIN_DIR/bin:\$PATH
PYTHONPATH=\$DOLFIN_DIR/lib/python$_pythonver/site-packages:\$PYTHONPATH
PKG_CONFIG_PATH=\$DOLFIN_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH
DYLD_LIBRARY_PATH=\$DOLFIN_DIR/lib:\$DYLD_LIBRARY_PATH
EOF
  popd
}

clean()
{
  rm -rfv $tmpdir
}

prepare
configure
build
package
#clean
